# fly.toml app configuration file generated for jiwar-telegram-bot on 2025-11-28T14:15:24+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jiwar-telegram-bot'
primary_region = 'cdg'

[build]

[env]
  NODE_ENV = 'production'

# [http_service]
#   internal_port = 3000
#   force_https = true
#   auto_stop_machines = 'off'
#   auto_start_machines = false
#   min_machines_running = 1
#   processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
